// <auto-generated />
using System;
using Brasileirao_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Brasileirao_App.Migrations
{
    [DbContext(typeof(BrasileiraoContext))]
    [Migration("20230919003423_CriandoTabelasIniciais")]
    partial class CriandoTabelasIniciais
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Brasileirao_App.Models.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdUf")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UFNavigationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UFNavigationId");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("Brasileirao_App.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPosicao")
                        .HasColumnType("int");

                    b.Property<int>("IdTime")
                        .HasColumnType("int");

                    b.Property<bool>("Lesionado")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Nr_Camisa")
                        .HasColumnType("int");

                    b.Property<int?>("PosicaoNavigationId")
                        .HasColumnType("int");

                    b.Property<bool>("Suspenso")
                        .HasColumnType("bit");

                    b.Property<int?>("TimeNavigationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PosicaoNavigationId");

                    b.HasIndex("TimeNavigationId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("Brasileirao_App.Models.Posicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posicoes");
                });

            modelBuilder.Entity("Brasileirao_App.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstadioNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadio")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EstadioNavigationId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("Brasileirao_App.Models.UF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("UFs");
                });

            modelBuilder.Entity("Brasileirao_App.Models.Estadio", b =>
                {
                    b.HasOne("Brasileirao_App.Models.UF", "UFNavigation")
                        .WithMany()
                        .HasForeignKey("UFNavigationId");

                    b.Navigation("UFNavigation");
                });

            modelBuilder.Entity("Brasileirao_App.Models.Jogador", b =>
                {
                    b.HasOne("Brasileirao_App.Models.Posicao", "PosicaoNavigation")
                        .WithMany()
                        .HasForeignKey("PosicaoNavigationId");

                    b.HasOne("Brasileirao_App.Models.Time", "TimeNavigation")
                        .WithMany()
                        .HasForeignKey("TimeNavigationId");

                    b.Navigation("PosicaoNavigation");

                    b.Navigation("TimeNavigation");
                });

            modelBuilder.Entity("Brasileirao_App.Models.Time", b =>
                {
                    b.HasOne("Brasileirao_App.Models.Estadio", "EstadioNavigation")
                        .WithMany()
                        .HasForeignKey("EstadioNavigationId");

                    b.Navigation("EstadioNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
